### ISSUE TITLE
Connecting to Discord throws error

### ISSUE THREAD

**Issue by noreliq** [elmadev/elmaonline-web#156]
![image](https://user-images.githubusercontent.com/2993084/227753750-11ae30e2-0d3a-436e-af8e-2ec41a5a1a68.png)

![image](https://user-images.githubusercontent.com/2993084/227753739-d3312ffc-3eb6-412d-a9a6-8da59ccd45e1.png)

**Comment by sunehs** [comment]
Some config values was accidentally removed. Fixed.
