### ISSUE TITLE
Installation Readme updates maybe

### ISSUE THREAD

**Issue by j-masci** [elmadev/elmaonline-web#237]
I ran into some issues, despite using node 16.15.0 (via nvm.. on windows) and yarn 3.x as stated in readme.

ChatGPT was helpful... to solve I just had to install node-fetch globally, and then re-install yarn.

```
npm install -g node-fetch
npm install -g yarn
yarn
yarn start
```

**Comment by j-masci** [comment]
ok i put this into wrong repo, meant for elmaonline-site

**Comment by sunehs** [comment]
shouldn't be needed with node 18 that we require now
